### PR TITLE
Added Simple Microservices Javaspringboot with MongoDB

### PR DESCRIPTION
**Pull request by iNitialM503**

### CODE REVIEW

**Comment by iNitialM503** [comment]
@knockcat Thanks Befor dear

**Comment by iNitialM503** [comment]
image

@knockcat Hello sir, why this repo has exclude label in hacktober

**Comment by knockcat** [comment]
I forget to add the hacktober-accepted tag , now I am adding but please let me know if it still show this after some time.

**Comment by iNitialM503** [comment]
hacktoberfest update every 15 min, but after 1 hour my PR not change from "Exclude to Waiting"

Maybe I got wrong step

**Comment by iNitialM503** [comment]
but you can check my new PR, I was added new project structure for Microservices Java Spring

**Pull request merged**
